### ISSUE TITLE
Potential ambiguity with role=combobox and contenteditable on MacOS

### ISSUE THREAD

**Issue by mrobinson** [w3c/html-aam#312] opened 2020-10-22 10:00 UTC
In [a recent Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1125165) there is an issue where a `<div contenteditable>` with a combobox role is presented as a textarea on macOS. Safari seems to present this element as a combobox. The 1.2 draft version of WAI-ARIA has text which allows the combobox role on elements that are not simply single-line text entries.

Should the HTML-AAM specification have text to the effect of "The combobox role maps to textarea unless there is another ARIA role" for macOS?

Here is the code in question:

```html
<div contenteditable="true" aria-label="search query" role="combobox" aria-autocomplete="list" aria-owns="owned_listbox" tabindex="0" aria-expanded="true"><p><br/></p></div>
```

**Comment by mrobinson** [comment] 2020-10-22 10:01
cc @cookiecrook @joanmarie

**Comment by mcking65** [comment] 2020-10-22 16:44
ARIA requires that an editable combobox be a single line text field.

**Comment by kloots** [comment] 2020-10-22 18:16
@mcking65 Regarding:

> ARIA requires that an editable combobox be a single line text field.

Does that mean this can be resolved by authors simply adding `aria-multiline="false"` to a `contenteditable` element?

**Comment by kloots** [comment] 2020-10-22 18:17
Also @mcking65 just curious as to why ARIA requires editable combobox be a single line text field? Why does this requirement exist?

**Comment by carmacleod** [comment] 2020-10-22 23:02
Happened to notice `aria-owns="owned_listbox"` in the above code. Just pointing out that ARIA 1.2 combobox prefers the use of `aria-controls="controlled_listbox"` instead of `aria-owns`, because technically, text fields aren't supposed to have children.

**Comment by kloots** [comment] 2020-10-23 01:01
@carmacleod are you suggesting the use of `aria-owns` is somehow contributing to the problem? Or are you just noting the spec change?

**Comment by kloots** [comment] 2020-10-23 01:19
Thought it was worth mentioning Chrome for Mac _is_ the outlier here. I just did a round of testing across popular screen reader + browser combinations to see how `role="combobox"` is supported on multiline text inputs created via the `contenteditable` attribute:


NVDA 2020.3 + Chrome 86 + mutiline text input: SUPPORTED
NVDA 2020.3 + Firefox 81 + mutiline text input: SUPPORTED
JAWS 2020 + Chrome 86 + mutiline text input: SUPPORTED
JAWS 2020  + Firefox 81 + mutiline text input: SUPPORTED
VoiceOver on Mac OS 10.15.7  + Safari 14 + mutiline text input: SUPPORTED
**VoiceOver + Chrome 86 + mutiline text input: NOT SUPPORTED**

**Comment by carmacleod** [comment] 2020-10-23 02:29
@kloots Noting the spec change.

**Comment by JAWS-test** [comment] 2020-10-23 04:23
> ARIA requires that an editable combobox be a single line text field.

I can imagine that in the future it might be good if role=combobox is also allowed on multiline input fields to allow combobox with multiple selection. Each line in the input field represents one value. In practice you can already see many comboboxes with multiple selection, but all of them do not work well with assistive technology because there are no corresponding ARIA roles and attributes.

**Comment by mrobinson** [comment] 2020-10-23 06:01
Note that the draft ARIA spec (1.2) seems a bit ambiguous as well. I think the relevant text is:

> A combobox functionally combines a named input field with the ability to assist value selection via a supplementary popup element. A combobox input MAY be either a single-line text field that supports editing and typing or an element that only displays the current value of the combobox.

I'm not sure if this MAY should be a MUST here.

**Comment by kloots** [comment] 2020-10-23 22:09
In the interest of unblocking @mrobinson on [Chromium issue 1125165](https://bugs.chromium.org/p/chromium/issues/detail?id=1125165). Is there at least agreement on `role="combobox"` being supported on `<div contenteditable="true">` so long as `aria-multiline` is set to "false"?

**Comment by carmacleod** [comment] 2020-10-24 03:14
> Is there at least agreement on `role="combobox"` being supported on `<div contenteditable="true">` so long as `aria-multiline` is set to "false"?

Yes, that is supported in the 1.2 spec, which will be moving to Candidate Recommendation status any day now. :)

**Comment by mcking65** [comment] 2021-01-04 01:31
@JAWS-test wrote:

> > ARIA requires that an editable combobox be a single line text field.
> 
> I can imagine that in the future it might be good if role=combobox is also allowed on multiline input fields to allow combobox with multiple selection. Each line in the input field represents one value. In practice you can already see many comboboxes with multiple selection, but all of them do not work well with assistive technology because there are no corresponding ARIA roles and attributes.


It gets tricky in part because up and down arrow are for navigating in/out/through the options, not for reading through a long input value.

Also, a multi-line text area with features like typeahead suggestions, like this GitHub comment editor, are not a combobox. A key feature of a combobox is that you are setting the entire value of the input by choosing from the list.

It seems that we'd want to encourage use of a pattern more like a pill list rather than a combobox for presentation of multiple values after selection. In a pill list, the UI typically offers users the ability to delete individual values, and, the selected values do not filter the presentation of the list of options.

At any rate, now that ARIA 1.2 is cleaning up the fundamental issues that prevented both emulation of select@size=1 and robust AT interoperability, we have the latitude to explore other ideas like multi-select and possibly even multi-line input. Although, the latter seems to me like a stretch given the way it would impact interaction patterns.

**Comment by scottaohara** [comment] 2021-04-15 23:53
testing in chrome with VoiceOver, seems that chromium with VoiceOver is still announcing the contenteditable element as "text" rather than "combobox" as Safari + VO correctly announces.

I'm unclear as to why this is an HTML AAM issue though.  The Chrome browser's accessibility panel correctly exposes the 'combobox' role...   the Chromium / VoiceOver pairing aren't respecting the explicit `role` that's been set.  So that seems a Chromium, Chromium/VO bug, and not a bug with this spec, since this spec outlines how native HTML features are mapped...and once you get ARIA roles/attributes involved, you're beyond the bounds of what's defined here.

All that said, _why_ a `contenteditable` element?  Even with `aria-multiline=false`, unless you then suppress the Enter key, and revise any pasted mult-line content into a single line string, it just seems like a lot of effort to do what an `input type=text` would allow for.  TBH, this is making me think an ARIA in HTML rule is needed to steer authors away from doing something like this, for all the reasons Matt has outlined above.

I'm open to suggestions / rational on what this spec needs to do to help here, and what use cases require this particular combobox pattern (also noting Carolyn's mention that the ARIA 1.1 combobox pattern should be forgotten post haste)... but without that, I'm leaning towards this not being an issue for this spec to resolve

**Closed as completed** 2021-05-12 12:39 UTC
